void readEeprom();
void writeEEPROM(float writeVariable1,float writeVariable2,float writeVariable3, float writeVariable4, float writeVariable5, float writeVariable6, float writeVariable7,float writeVariable8);
void writeEEPROMVariables(short variable);
extern float valorPD;
extern float valorPR;
extern float valorAGC;
extern float valorIsal;
extern float valorVsal;
extern float valorVexc;
extern float valorVaux;
extern float valorVlinea; 
extern float bitsResolucion; 

extern String VARIABLE1;
extern String VARIABLE2;
extern String VARIABLE3;
extern String VARIABLE4;
extern String VARIABLE5;
extern String VARIABLE6;
extern String VARIABLE7;
extern String VARIABLE8;

extern String UNIDAD1;
extern String UNIDAD2;
extern String UNIDAD3;
extern String UNIDAD4;
extern String UNIDAD5;
extern String UNIDAD6;
extern String UNIDAD7;
extern String UNIDAD8;
