void leerBotones();
void setup_menu();
void leerPagina(int pagina);
void mostrarnombreVariables();
void mostrarValores(float a,float b,float c,float d, float e,float f,float g,float h);
void mostrarTemperatura(float temperatura);
void mostrarCalibraciones();
void mostrarcalibracionSerial();
void fn_mediciones();
void fn_configuracion();
void fn_mas_configuraciones();
void fn_temperatura();
void fn_configuraciones_calibraciones();
void fn_configuraciones_serial();
void mostrarnombredeEquipo();
